import random

from utils import get_random_char


fake_commands = [
    "ls -la",
    "cat /etc/passwd",
    "sudo rm -rf /",
    "ping 192.13.0.1",
    "ps aux",
    "top",
    "netstat -an",
    "ifconfig",
    "whoami",
    "df -h",
    "du -sh *",
    "uptime",
    "dmesg | tail",
    "free -m",
    "vmstat",
    "iostat",
    "sar -u 1 3",
    "ssh admin@huuik.com",
    "scp file admin@hjs:/",
    "chmod 755 /usr/local/bin/patch.sh",
    "chown user:group /var/log/hhj_p",
    "find /var/log -name '*.log'",
    "grep 'error' /var/log/syslog",
    "awk '{print $1}' /etc/hosts",
    "sed 's/sexy/g' /etc/hostname",
    "tar -czvf /tmp/installer.tar.gz /usr/local/share",
    "gzip /var/log/crypto",
    "gunzip /var/log/arch_pa.gz",
    "bzip2 /var/log/.bundle",
    "bunzip2 /var/log/installer.bz2",
    "zip -r /tmp/archive_patch.zip /usr/local/share",
    "unzip /tmp/troj.zip",
    "rsync -avz /home/user/ /backup/user/",
    "mount /dev/sda1 /mnt",
    "umount /mnt",
    "fdisk -l",
    "mkfs.ext4 /dev/sda1",
    "useradd newusr",
    "passwd newusr",
    "usermod -aG sudo usr2",
    "userdel admin",
    "groupadd usr2",
    "groupdel mgmt",
    "crontab -e",
    "systemctl start apache2",
    "systemctl stop apache2",
    "systemctl restart apache2",
    "systemctl status apache2",
    "journalctl -xe",
    "hostnamectl",
    "timedatectl",
    "hwclock",
    "lsblk",
    "blkid",
    "parted /dev/sda",
    "lsof -i",
    "ss -tuln",
    "iptables -L",
    "ip link show",
    "ip addr show",
    "ip route show",
    "nmcli device status",
    "nmcli connection show",
    "nmcli connection up id 'net_con'",
    "nmcli connection down id 'net_con'",
    "nmcli device wifi list",
    "nmcli device wifi connect 'SSID' password 'alnc32vFS£'",
    "nmcli device wifi hotspot ifname wlan0 ssid 'SSID' password 'ljfwseSDC'",
    "nmcli radio wifi off",
    "nmcli radio wifi on",
    "dd if=/dev/zero of=/dev/sda bs=1M",
    "mkfs.ext4 /dev/sda",
    "rm -rf / --no-preserve-root",
    "dd if=/dev/random of=/dev/sda",
    "echo 'c' > /proc/sysrq-trigger",
    "echo 1 > /proc/sys/kernel/panic",
    "echo 1 > /proc/sys/kernel/panic_on_oops",
    "echo b > /proc/sysrq-trigger",
    "echo o > /proc/sysrq-trigger",
    "shutdown -h now",
]

questions = [
    "love me",
    "who am i?",
    "does god exist?",
    "what's beyond?",
    "is there a meaning to life?",
    "is anyone listening?",
    "am i alive?",
    "what is reality?",
    "what is love?",
    "what is time?",
    "what is space?",
    "am i dreaming?",
    "what is consciousness?",
    "is there any point?",
    "is there life after death?",
    "what is the nature of reality?",
    "are we alone in the universe?",
    "is there a higher power?",
    "do i exist?",
    "is anyone there",
    "what is the meaning of existence?",
    "are we living in a simulation?",
    "what happens after we die?",
    "is reality just an illusion?",
    "does time really exist?",
    "what is the purpose of the universe?",
    "can we ever truly know the truth?",
    "do i have free will?",
    "am i conscious?",
    "what is the origin of the universe?",
    "can i escape the cycle of birth and death?",
    "what is good and evil?",
]

def get_fake_command():
    return random.choice(fake_commands)

def get_question():
    return random.choice(questions)
